# typed: false
# frozen_string_literal: true

# Homebrew formula for mosskeys-witness.
#
# The install / package name and the command it installs are both
# `mosskeys-witness`. This formula installs the prebuilt, signed binary attached
# to the GitHub Release (not a from-source build), so it shares the exact
# artifact that ships with a CycloneDX SBOM, SHA-512 checksums, a keyless cosign
# signature, and SLSA build provenance. See RELEASING.md in moss-piglet/mosskeys-witness.
#
# This file is generated by .github/scripts/render-homebrew-formula.sh on each
# tagged release and committed to the tap repo
# (moss-piglet/homebrew-mosskeys-witness). Do not hand-edit checksums here.
class MosskeysWitness < Formula
  desc "Post-quantum-native C2SP tlog-witness (Ed25519 0x04 + ML-DSA-44 0x06)"
  homepage "https://mosskeys.com"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.1.0/mosskeys-witness-0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "5ed53da7d0fa78d84f56216c8db3a5f0dc975a9f9c82fd8117d72f831e442651"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.1.0/mosskeys-witness-0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "2c6b27b315d265a22cec37f318ec3b8e932d0af06f41346ff5b2cb9863cb3431"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.1.0/mosskeys-witness-0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "d688af8060e9400c79a770ac11b2df588d718f9dcbe53a2d95a71f78639308f8"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.1.0/mosskeys-witness-0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c10aa6e8be9caeca7dfe5e6540ac3314fc97eac5f1945ca2fe968a3cfc73d646"
    end
  end

  def install
    bin.install "mosskeys-witness"
  end

  test do
    assert_match "mosskeys-witness #{version}", shell_output("#{bin}/mosskeys-witness --version")
  end
end
