# typed: false
# frozen_string_literal: true

# Homebrew formula for mosskeys-witness.
#
# The install / package name and the command it installs are both
# `mosskeys-witness`. This formula installs the prebuilt, signed binary attached
# to the GitHub Release (not a from-source build), so it shares the exact
# artifact that ships with a CycloneDX SBOM, SHA-512 checksums, a keyless cosign
# signature, and SLSA build provenance. See RELEASING.md in moss-piglet/mosskeys-witness.
#
# This file is generated by .github/scripts/render-homebrew-formula.sh on each
# tagged release and committed to the tap repo
# (moss-piglet/homebrew-mosskeys-witness). Do not hand-edit checksums here.
#
# SEED COPY: v0.1.0 has not been tagged yet, so the sha256 values below are
# placeholders (all zeros). The first tag's `update-tap` job rewrites this file
# with real checksums; refresh this in-repo copy from the tap after the release.
class MosskeysWitness < Formula
  desc "Post-quantum-native C2SP tlog-witness (Ed25519 0x04 + ML-DSA-44 0x06)"
  homepage "https://mosskeys.com"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.1.0/mosskeys-witness-0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.1.0/mosskeys-witness-0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.1.0/mosskeys-witness-0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-witness/releases/download/v0.1.0/mosskeys-witness-0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "mosskeys-witness"
  end

  test do
    assert_match "mosskeys-witness #{version}", shell_output("#{bin}/mosskeys-witness --version")
  end
end
